[package]
name = "d"
version = "0.0.1"
authors = ["Alexandre Côté <a.cote@2kloc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rff = "0.3"
regex = "1"
structopt = "0.3"
shellexpand = "2.1"
