name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: d
            asset_name: d-linux-amd64
          - os: macos-26-intel
            artifact_name: d
            asset_name: d-macos-amd64
          - os: macos-latest
            artifact_name: d
            asset_name: d-macos-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --locked

    - name: Generate assets
      run: tar -cvzf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}.sh -C target/release ${{ matrix.artifact_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.asset_name }}.tar.gz